[build]
  base = "qaest-mvp/frontend"
  publish = "build"
  command = "CI=false npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://qaest.onrender.com"
  CI = "false"