services:
  # Backend service
  - type: web
    name: qaest-backend
    runtime: node
    buildCommand: cd qaest-mvp/backend && npm install
    startCommand: cd qaest-mvp/backend && node server-basic.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000

  # Frontend service
  - type: web
    name: qaest-frontend
    runtime: static
    buildCommand: cd qaest-mvp/frontend && npm install && npm run build
    staticPublishPath: ./qaest-mvp/frontend/build
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html